sudo: required

language: java

services:
  - xvfb

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before-script:
  - "export DISPLAY=99:0"

script:
  - "export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`"
