sudo: required
language: java

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

script: 
  - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
  - mvn test -B
